version: "3.8"

services:
    metasdkcpp-build:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: metasdkcpp-container
        image: metasdkcpp
        working_dir: /app
        volumes:
            - ./:/app/src
        command: >
            bash -c "
                set -e
                mkdir build_docker
                cmake -S /app/src -B /app/build_docker
                cmake --build /app/build_docker --parallel
                cd /app/build_docker
                ctest --output-on-failure --output-junit test_sdkcpp.xml
                # ./metasdkcpp_core_exe
            "
